#!/usr/bin/env bash

set -e

EMPTY=$([ $(ls -A /var/www | grep -v "bashrc" | wc -l) -eq 0 ] && echo 'true' || echo 'false')

if [ $EMPTY == 'true' ]; then
    echo "No files found in /var/www, attempting to get lock"
    (
        if flock -n 9; then
            echo 'Got lock - installing virtual environment'
            mkdir public
            python3 -m venv ${VIRTENV}
            source ${VIRTENV}/bin/activate
            python --version
            pip --version
            pip install --no-cache-dir --upgrade pip mysqlclient flask uwsgi
            cp -r /usr/src/* /var/www
        else
            echo 'No lock, exiting'
            exit
        fi
    ) 9>/var/www/alockfile

    rm -f /var/www/alockfile
else
    echo "Upgrading default python modules"
    (
        if flock -n 9; then
            echo 'Got lock - upgrading virtual environment'
            source ${VIRTENV}/bin/activate
            python --version
            pip --version
            pip install --no-cache-dir --upgrade pip mysqlclient flask uwsgi
        else
            echo 'No lock, exiting'
            exit
        fi
    ) 9>/var/www/alockfile

    rm -f /var/www/alockfile
fi
